# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        python3 -m pytest

    - name: Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.API_SERVER_HOST }}
        username: ${{ secrets.API_SERVER_SSH_ID }}
        key: ${{ secrets.API_SERVER_SSH }}
        port: ${{ secrets.API_SERVER_PORT }}
        script: |
          DATE=$(date "+%y.%m.%d")
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PW }}
          docker build -t ${{ secrets.REGISTRY_001 }}/parser_api:$DATE ./backend-parser/
          docker push ${{ secrets.REGISTRY_001 }}/parser_api:$DATE 
          docker build -t ${{ secrets.REGISTRY_002 }}/parser_api ./backend-parser/   
          docker push ${{ secrets.REGISTRY_002 }}/parser_api
