# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest

    - name: Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.API_SERVER_HOST }}
        username: ${{ secrets.API_SERVER_SSH_ID }}
        key: ${{ secrets.API_SERVER_SSH }}
        port: ${{ secrets.API_SERVER_PORT }}
        script: |
          $DATE=$(date "+%y.%m.%d")
          docker rmi $(docker images -f "dangling=true" -q)
          docker build . -t parser_api:$DATE
          docker push ${{ secrets.REPOSITORY }}/parser_api:$DATE
